name: Mirror Merged PRs from Upstream

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  mirror_prs:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.branches.outputs.branches }}

    steps:
    - name: Checkout the downstream repository
      uses: actions/checkout@v2
      with:
        repository: TerraTheUnwisest/PlanetoidSS14
        token: ${{ secrets.GH_PAT }}

    - name: Configure Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"

    - name: Fetch PRs from upstream
      run: |
        git remote add upstream https://github.com/space-wizards/space-station-14.git
        git fetch upstream

    - name: List merged PRs
      id: list_prs
      run: |
        # Fetch the merged PRs from upstream
        curl -H "Authorization: token ${{ secrets.GH_BPAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/space-wizards/space-station-14/pulls?state=closed \
          > merged_prs_raw.json
        # Output the raw JSON for debugging
        cat merged_prs_raw.json
        # Extract the PR numbers
        cat merged_prs_raw.json | jq '.[] | select(.merged_at != null) | .number' > merged_prs.txt
        cat merged_prs.txt

    - name: Create new branches
      id: branches
      run: |
        branches=""
        while read pr_number; do
          # Get PR details
          pr=$(curl -H "Authorization: token ${{ secrets.GH_BPAT }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/space-wizards/space-station-14/pulls/$pr_number)

          pr_title=$(echo $pr | jq -r '.title')
          pr_body=$(echo $pr | jq -r '.body')
          pr_merge_commit=$(echo $pr | jq -r '.merge_commit_sha')

          # Debugging logs
          echo "PR Number: $pr_number"
          echo "PR Title: $pr_title"
          echo "PR Body: $pr_body"
          echo "PR Merge Commit: $pr_merge_commit"

          # Create a new branch based on the merge commit
          git checkout -b mirror-pr-$pr_number $pr_merge_commit

          # Push the new branch to the downstream repository
          git push origin mirror-pr-$pr_number

          # Track created branches
          branches="$branches mirror-pr-$pr_number"
        done < merged_prs.txt

        echo "::set-output name=branches::$branches"

    - name: Clean up
      run: |
        rm merged_prs.txt

  create_prs:
    runs-on: ubuntu-latest
    needs: mirror_prs
    if: ${{ success() }}

    steps:
    - name: Create PRs with the bot
      run: |
        branches="${{ needs.mirror_prs.outputs.branches }}"
        for branch in $branches; do
          # Create a new PR in the downstream repository
          curl -X POST -H "Authorization: token ${{ secrets.GH_BPAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/TerraTheUnwisest/PlanetoidSS14/pulls \
            -d "$(jq -n --arg title "MIRROR: $branch" --arg body "This PR mirrors the changes from the upstream PR." --arg base "master" --arg head "$branch" \
              '{title: $title, body: $body, base: $base, head: $head}')"
        done

  cleanup_branches:
    runs-on: ubuntu-latest
    needs: create_prs
    if: ${{ success() }}

    steps:
    - name: Checkout the downstream repository
      uses: actions/checkout@v2
      with:
        repository: TerraTheUnwisest/PlanetoidSS14
        token: ${{ secrets.GH_PAT }}

    - name: Configure Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"

    - name: Fetch all branches
      run: |
        git fetch --all

    - name: Delete old mirror branches
      run: |
        branches="${{ needs.create_prs.outputs.branches }}"
        for branch in $branches; do
          git push origin --delete $branch
        done
